AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/MethodLength:
  Max: 7

Style/Documentation:
  Enabled: false
